export const GET_SUMMARY_ACTION = 'GET_SUMMARY_ACTION';
export const GET_INFORMATION_COUNTRY = 'GET_INFORMATION_COUNTRY';
export const GET_CASE_COUNTRY = 'GET_CASE_COUNTRY';
export const GET_CASE_COUNTRY_BY_DATE = 'GET_CASE_COUNTRY_BY_DATE';
export const REMOVE_DATA_CASE_COUNTRY_BY_DATE_AND_INFORMATION_COUNTRY = 'REMOVE_DATA_CASE_COUNTRY_BY_DATE_AND_INFORMATION_COUNTRY';
export const SORT_MOST_TOTAL_CONFIRMED_CASE = 'SORT_MOST_TOTAL_CONFIRMED_CASE';
export const SORT_HIGHEST_NUMBER_DEATHS = 'SORT_HIGHEST_NUMBER_DEATHS';
export const SORT_DEFAULT = 'SORT_DEFAULT';