export const GET_SUMMARY_ACTION = 'GET_SUMMARY_ACTION';
export const SORT_MOST_TOTAL_CONFIRMED_CASE = 'SORT_MOST_TOTAL_CONFIRMED_CASE';
export const SORT_HIGHEST_NUMBER_DEATHS = 'SORT_HIGHEST_NUMBER_DEATHS';
export const SORT_DEFAULT = 'SORT_DEFAULT';